FROM nginx:latest
#FROM nginxdemos/hello:latest
ADD ./css  /usr/share/nginx/html/css
ADD ./fancybox /usr/share/nginx/html/fancybox
ADD ./fonts /usr/share/nginx/html/fonts 
ADD ./js /usr/share/nginx/html/js
ADD ./images /usr/share/nginx/html/images 
ADD ./index.html /usr/share/nginx/html/index.html
ADD ./conf.d/hello.conf /etc/nginx/conf.d/hello.conf
